	<title>
	
	
	
	Roy Murdock</title>

	

	<div id="main">

	<article>

	<header>
	<h1>
	<a href="#"></a>
	</h1>
	</header>

	<div align="center"><img style="height:auto; width:auto; max-width:200px; max-height:200px;" src="http://roymurdock.com/koken/RMFace.png"></div>
<br>
<br>
<hr>
<br>
<br>
<p class="" align="center">Hello, my name is Roy Murdock. I am the creator of this site and the sole author of its contents.</p><p class="" align="center">I write these essays in order to understand and predict through thought, research, and analysis. </p><p class="" align="center">My main areas of interest are economics, technology, finance, and philosophy.</p><p class="" align="center">I value <b>integrity</b>, <b>honesty</b>, and <b>reason</b>. I hope this is reflected in my writing.</p><p class="" align="center">You can <a href="mailto:murdock.roy@gmail.com" target="_blank">send me an email</a> if you'd like to get in touch. Thank you for reading.</p>
	</article>

	</div>

	<script>$K.ready();</script>
<script>$K.location = $.extend($K.location, {"here":"\/pages\/about\/","parameters":{"page":1,"url":"\/pages\/about\/","base_folder":"\/","_pjax":"#target"},"page_class":"k-source-page k-lens-page"});$(window).trigger('k-pjax-end');</script><style id="koken_custom_css">@font-face {
    font-family: 'equity_text_aregular';
    src: url('equity_text_a_regular-webfont.eot');
    src: url('equity_text_a_regular-webfont.eot?#iefix') format('embedded-opentype'),
         url('equity_text_a_regular-webfont.woff') format('woff'),
         url('equity_text_a_regular-webfont.ttf') format('truetype'),
         url('equity_text_a_regular-webfont.svg#equity_text_aregular') format('svg');
    font-weight: normal;
    font-style: normal;

    </style>