	<title>
	
	
	Roy Murdock</title>

<div id="main" class="timeline">

	
	

	
	<h1 class="top">
	<a href="/timeline/2014/01/18/" title="View everything published this day" data-koken-internal>
	</a>
	</h1>

	<div class="event">

	</div>
	<hr>
	<h1 class="top">
	<a href="/timeline/2013/11/04/" title="View everything published this day" data-koken-internal>
	</a>
	</h1>

	<div class="event">

	<time datetime="2013-11-04T20:43:06+00:00" >
	November 4, 2013
</time>	
<span class="text">

	<h1>
	<a href="/essays/2013/11/snapchat-is-intrinsically-worthless/" class="essay_title" title="View Am I Going Insane? Snapchat is Intrinsically Worthless" data-koken-internal>Am I Going Insane? Snapchat is Intrinsically Worthless</a>&nbsp;&nbsp;<span class="item_meta">(<a href="http://roymurdock.com/essays/2013/11/snapchat-is-intrinsically-worthless/#disqus_thread" data-disqus-identifier="koken_disqus_essay_3"></a>)</span>	</h1>

	<div class="item">

	<a href="/essays/2013/11/snapchat-is-intrinsically-worthless/" title="View Am I Going Insane? Snapchat is Intrinsically Worthless" class=".top" data-koken-internal>
	<div class="media">

	
	<noscript>
	<img width="100%" alt="Snapchat Header" src="http://roymurdock.com/koken/storage/cache/images/000/022/snapchatbanner,large.png?1383598234" />
</noscript>
<img data-alt="Snapchat Header" data-respond-to="width" data-presets="tiny,60,29 small,100,49 medium,480,234 medium_large,705,344 large,705,344 xlarge,705,344 huge,705,344" data-base="http://roymurdock.com/koken/storage/cache/images/000/022/snapchatbanner," data-extension="png?1383598234"/>

	
	
	</div>

	</a>

	<p class="caption">
	While Snapchat's valuation is nowhere close to that of Apple and Facebook, it is surprisingly close to stable, established companies with actual revenue streams. Why have investors put such a high price tag on what seems to be a silly messaging app?	<a href="/essays/2013/11/snapchat-is-intrinsically-worthless/" class="read_more" title="View Am I Going Insane? Snapchat is Intrinsically Worthless" data-koken-internal>more</a>
	</p>

	
	
	</span>

	</div>

	</div>
	<hr>
	<h1 class="top">
	<a href="/timeline/2013/10/05/" title="View everything published this day" data-koken-internal>
	</a>
	</h1>

	<div class="event">

	<time datetime="2013-10-05T18:22:36+00:00" >
	October 5, 2013
</time>	
<span class="text">

	<h1>
	<a href="/essays/2013/10/google-is-taking-apples-niche/" class="essay_title" title="View The Death of the iPhone" data-koken-internal>The Death of the iPhone</a>&nbsp;&nbsp;<span class="item_meta">(<a href="http://roymurdock.com/essays/2013/10/google-is-taking-apples-niche/#disqus_thread" data-disqus-identifier="koken_disqus_essay_1"></a>)</span>	</h1>

	<div class="item">

	<a href="/essays/2013/10/google-is-taking-apples-niche/" title="View The Death of the iPhone" class=".top" data-koken-internal>
	<div class="media">

	
	<noscript>
	<img width="100%" alt="custom_oembed_1.jpg" src="http://roymurdock.com/koken/storage/cache/images/custom/custom_oembed_1-jpg/large.jpg?1380997692" />
</noscript>
<img data-alt="custom_oembed_1.jpg" data-respond-to="width" data-presets="tiny,60,45 small,100,75 medium,480,360 medium_large,480,360 large,480,360 xlarge,480,360 huge,480,360" data-base="http://roymurdock.com/koken/storage/cache/images/custom/custom_oembed_1-jpg/" data-extension="jpg?1380997692"/>

	
	
	</div>

	</a>

	<p class="caption">
	Apple has long been the champion of meeting (and exceeding) customer expectations. What happens when big data and responsive technology enter the equation?	<a href="/essays/2013/10/google-is-taking-apples-niche/" class="read_more" title="View The Death of the iPhone" data-koken-internal>more</a>
	</p>

	
	
	</span>

	</div>

	</div>
	<hr>
	<h1 class="top">
	<a href="/timeline/2013/09/21/" title="View everything published this day" data-koken-internal>
	</a>
	</h1>

	<div class="event">

	<time datetime="2013-09-21T22:12:20+00:00" >
	September 21, 2013
</time>	
<span class="text">

	<h1>
	<a href="/essays/2013/09/how-useful-is-the-new-iphone/" class="essay_title" title="View How Useful Is the New iPhone 5s?" data-koken-internal>How Useful Is the New iPhone 5s?</a>&nbsp;&nbsp;<span class="item_meta">(<a href="http://roymurdock.com/essays/2013/09/how-useful-is-the-new-iphone/#disqus_thread" data-disqus-identifier="koken_disqus_essay_2"></a>)</span>	</h1>

	<div class="item">

	<a href="/essays/2013/09/how-useful-is-the-new-iphone/" title="View How Useful Is the New iPhone 5s?" class=".top" data-koken-internal>
	<div class="media">

	
	<noscript>
	<img width="100%" alt="iphone5s.jpeg" src="http://roymurdock.com/koken/storage/cache/images/000/006/iphone5s,large.jpeg?1379898585" />
</noscript>
<img data-alt="iphone5s.jpeg" data-respond-to="width" data-presets="tiny,60,36 small,100,60 medium,480,288 medium_large,640,384 large,640,384 xlarge,640,384 huge,640,384" data-base="http://roymurdock.com/koken/storage/cache/images/000/006/iphone5s," data-extension="jpeg?1379898585"/>

	
	
	</div>

	</a>

	<p class="caption">
	While the new 5s and 5c may keep customers coming back to Apple, they will not bring about any serious change in the smartphone world, and stagnation leads to decay and eventual death. Let's go through the list of 5s and iOS7 upgrades and ask ourselves…	<a href="/essays/2013/09/how-useful-is-the-new-iphone/" class="read_more" title="View How Useful Is the New iPhone 5s?" data-koken-internal>more</a>
	</p>

	
	
	</span>

	</div>

	</div>
	<hr>	
	
	<script>$K.keyboardScroll('.item', 0);</script>

	
</div>

	<script>$K.ready();</script>
<script>$K.location = $.extend($K.location, {"here":"\/","parameters":{"page":1,"url":"\/","base_folder":"\/","_pjax":"#target"},"page_class":"k-source-timeline k-lens-timeline"});$(window).trigger('k-pjax-end');</script><style id="koken_custom_css">@font-face {
    font-family: 'equity_text_aregular';
    src: url('equity_text_a_regular-webfont.eot');
    src: url('equity_text_a_regular-webfont.eot?#iefix') format('embedded-opentype'),
         url('equity_text_a_regular-webfont.woff') format('woff'),
         url('equity_text_a_regular-webfont.ttf') format('truetype'),
         url('equity_text_a_regular-webfont.svg#equity_text_aregular') format('svg');
    font-weight: normal;
    font-style: normal;

    </style>